
server {
    listen 80;
    server_name chaitu.com;
    access_log /var/log/nginx/wordle_project.access.log;
    error_log /var/log/nginx/wordle_project.error.log;

    location /static/ {
        alias /app/staticfiles/; 
    }

    location / {
        include proxy_params;
        proxy_pass http://django:8000;
    }

}
